import type { Product } from '../types/product';

/**
 * Product wording in the page's language. English is the source of truth;
 * the Arabic fields are used when present and the site is in Arabic, and
 * anything untranslated simply stays English.
 */
export function pName(p: Pick<Product, 'name' | 'nameAr'>, lang: string): string {
  return lang === 'ar' && p.nameAr ? p.nameAr : p.name;
}

export function pDesc(p: Pick<Product, 'shortDescription' | 'shortDescriptionAr'>, lang: string): string {
  return lang === 'ar' && p.shortDescriptionAr ? p.shortDescriptionAr : p.shortDescription;
}

/* Spec sheets are typed as free key:value text, but the keys repeat —
   so the labels translate through a lookup, and unknown keys pass
   through untouched. Values stay as typed. */
const SPEC_LABELS: Record<string, string> = {
  cpu: 'المعالج',
  processor: 'المعالج',
  ram: 'الذاكرة',
  memory: 'الذاكرة',
  storage: 'التخزين',
  ssd: 'التخزين SSD',
  hdd: 'القرص الصلب',
  display: 'الشاشة',
  screen: 'الشاشة',
  monitor: 'الشاشة',
  gpu: 'كرت الشاشة',
  graphics: 'كرت الشاشة',
  battery: 'البطارية',
  weight: 'الوزن',
  os: 'نظام التشغيل',
  'operating system': 'نظام التشغيل',
  warranty: 'الضمان',
  resolution: 'الدقة',
  lens: 'العدسة',
  ir: 'الرؤية الليلية',
  'ir range': 'مدى الرؤية الليلية',
  'night vision': 'الرؤية الليلية',
  power: 'القدرة',
  capacity: 'السعة',
  voltage: 'الفولتية',
  current: 'التيار',
  ports: 'المنافذ',
  connectivity: 'الاتصال',
  color: 'اللون',
  type: 'النوع',
  efficiency: 'الكفاءة',
  channels: 'القنوات',
  zoom: 'الزوم',
  brand: 'الماركة',
  model: 'الموديل',
  size: 'الحجم',
  speed: 'السرعة',
  frequency: 'التردد',
  output: 'الخرج',
  input: 'الدخل',
  'refresh rate': 'معدل التحديث',
  'response time': 'زمن الاستجابة',
  keyboard: 'لوحة المفاتيح',
  camera: 'الكاميرا',
  audio: 'الصوت',
  microphone: 'المايكروفون',
  'wi-fi': 'واي فاي',
  wifi: 'واي فاي',
  bluetooth: 'بلوتوث',
  'cycle life': 'عدد الدورات',
  cycles: 'عدد الدورات',
  cells: 'الخلايا',
  protection: 'الحماية',
  certification: 'الشهادات',
  dimensions: 'الأبعاد',
  mppt: 'MPPT',
  'pv input': 'دخل الألواح',
  'surge power': 'قدرة الذروة',
  'battery voltage': 'فولتية البطارية',
  interface: 'المنفذ',
  'form factor': 'الشكل',
  'read speed': 'سرعة القراءة',
  'write speed': 'سرعة الكتابة',
  'operating temperature': 'درجة حرارة التشغيل',
  'poe ports': 'منافذ PoE',
  'ethernet standards': 'معايير الشبكة',
  'device type': 'نوع الجهاز',
  'surge protection': 'الحماية من الصواعق',
  'port speed': 'سرعة المنافذ',
  'poe priority': 'أولوية PoE',
  'esd protection': 'حماية ESD',
  'operating modes': 'أوضاع التشغيل',
  'status indicators': 'مؤشرات الحالة',
  'nominal voltage': 'الفولتية الاسمية',
  'primary function': 'الوظيفة الأساسية',
  'product type': 'نوع المنتج',
  'current type': 'نوع التيار',
  'suitable for': 'مناسب لـ',
  'total ports': 'مجموع المنافذ',
  'thermal resolution': 'الدقة الحرارية',
  'power supply': 'التغذية',
  'image sensor': 'مستشعر الصورة',
  'compatibility': 'التوافق',
  'uplink ports': 'منافذ الربط',
  'flow control': 'التحكم بالتدفق',
  'switching method': 'طريقة التبديل',
  'communication': 'الاتصال',
  'rated capacity': 'السعة المقننة',
  'installation type': 'نوع التركيب',
  'battery application': 'استخدام البطارية',
  'battery category': 'فئة البطارية',
  'system voltage': 'فولتية النظام',
  'use': 'الاستخدام',
  'capacity class': 'فئة السعة',
  'sfp uplink ports': 'منافذ SFP للربط',
  'uplink speed': 'سرعة الربط',
  'sequential write': 'الكتابة التسلسلية',
  'sequential read': 'القراءة التسلسلية',
  'controller': 'المتحكم',
  'rated output power': 'قدرة الخرج المقننة',
  'maximum pv input power': 'أقصى دخل ألواح',
  'maximum pv input voltage': 'أقصى فولتية ألواح',
  'protection & warranty': 'الحماية والضمان',
  'rated power': 'القدرة المقننة',
  'output voltage': 'فولتية الخرج',
  'input voltage': 'فولتية الدخل',
  'battery type': 'نوع البطارية',
  'network': 'الشبكة',
  'ports & connectivity': 'المنافذ والاتصال',
  'video compression': 'ضغط الفيديو',
  'ir distance': 'مدى الرؤية الليلية',
  'wide dynamic range': 'المدى الديناميكي الواسع',
  'ingress protection': 'درجة الحماية',
  'maximum efficiency': 'أقصى كفاءة',
  'maximum ac output power': 'أقصى قدرة خرج AC',
  'max efficiency': 'أقصى كفاءة',
  'ac output voltage': 'فولتية خرج AC',
  'ac input voltage': 'فولتية دخل AC',
};

export function specLabel(name: string, lang: string): string {
  if (lang !== 'ar') return name;
  return SPEC_LABELS[name.trim().toLowerCase()] ?? name;
}
